### ISSUE TITLE
《尋找創業夥伴🔥 》Golang 工程師-[台北/遠端][股權+底薪] 酷卡科技股份有限公司

### ISSUE THREAD

**Issue by oscar-ko** [b2etw/jobs#28]
小弟我開發了全球第一個臉書式的語言學習社群 (就是學語言的 FB 啦)

這個系統的特點就是：**AI 輔助的社交型學習**

很幸運去年我在FB找到3個伙伴一起創業, Golangx1, iOSx1, Androidx1, 也有了股東支持, 這個平台已經開發快10個月了，預計年底上線。
我們公司目前有一項專利正在申請中，也剛取得 SiTi臺北市產

業發展獎勵補助計畫。

目前還需要下面人才
- Golang 工程師 

🔥 這是創業邀約，你會擁有股權，我們一起當老板，歡迎私訊我喔~

![CoolCard-Golang](https://user-images.githubusercontent.com/33344160/153368456-d898efde-de75-4dc5-8f67-0a8b1a74d42e.png)

**Comment by Jian-Min-Huang** [comment]
標題是Go? 內容是徵Swift ?

**Comment by oscar-ko** [comment]
哈，我居然寫錯了，昏倒。。。謝謝你的提醒

**Comment by oscar-ko** [comment]
> 標題是Go? 內容是徵Swift ?

哈，我居然寫錯了，昏倒。。。謝謝你的提醒
