### ISSUE TITLE
[徵才] 叡揚資訊股份有限公司 / Jr. Backend

### ISSUE THREAD

**Issue by a26007565** [b2etw/jobs#4]
# 公司名稱
叡揚資訊股份有限公司

# 公司地址
10461台北市中山區德惠街9號

# 公司網站
https://www.gss.com.tw/

# 職缺與薪資範圍
* Jr. Backend Engineer (40~70K/Month)

# 職務說明
## Jr. Backend Engineer

與公司內的前端部門合作開發雲端產品 [BizForm](https://www.gsscloud.com/tw/vital/bizform)
主要內容為商業邏輯分析、資料庫設計、程式碼撰寫、系統測試、上線與維運階段的問題回應與處理
所使用到的技術為 ASP.Net Core, SignalR, NHibernate, Multi-Tenancy...

除此之外，我們在公司雲端產品開發團隊中，
除Bizform單一產品外，也有CRM產品、會計系統、集點系統、資料分析、基礎建設等服務，角色上也還有前端工程師、使用者體驗、介面設計師們互動密切。

# 職缺要求
#### Must Have
* C#
* git
* 基本邏輯能力
* RESTful API
* 對程式開發有熱忱
* 樂於分享討論並能與團隊間溝通解決問題
 
#### Nice to Have
* Unit Test
* 整合過 CI/CD 的經驗

# 面試流程
* 主管面試

# 公司介紹
```
叡揚是一個 33 年的純軟體公司，約 500 人，老闆人友善，投入不少心力在臺灣資訊軟體圈
​
產品種類主要為 B2B 軟體，包含公文、CRM、企業表單流程、知識管理、人事薪資差勤、會計......等多種軟體
公司業務從代理產品、專案、套專軟體、雲端服務都有
```

# 工作福利

* 年終獎金、端午禮金、中秋禮金
* 員工分紅
* 婚喪喜慶津貼
* 生日禮金
* 壽星當月享有一日生日假(給薪)
* 員工介紹獎金
* 資深員工獎(獎金、禮品)、傑出貢獻獎(獎金)
* 尾牙、家庭日、樂活日、員工慶生會、社團活動
* 電影日(事業處聯合舉辦)、聖誕節活動、不定期歡聚活動
* 新人輔導員制度、新人茶會
* 國內外員工旅遊補助
* 父親節、母親節禮品
* 每週咖啡日
* 週休二日、彈性上下班
* 完善教育訓練制度
* 享有勞保、健保、團保、勞退提撥
* 年度休假
* 年度員工健康檢查(含新人體檢)
* 每月部門交流活動

# 聯絡方式

* Wilber Chen 02-25867890#10366 <wilber_chen@gss.com.tw>
* Bear Lee 02-25867890#10269 <bear_lee@gss.com.tw>

**Comment by a26007565** [comment]
@Jian-Min-Huang 可以幫忙 reopen嗎

**Comment by Jian-Min-Huang** [comment]
可以，就直接是為你們已經重新repost
