### ISSUE TITLE
[徵才][台北/信義]_Ubiquiti_Backend Engineer - node.js

### ISSUE THREAD

**Issue by Uiler105** [b2etw/jobs#46]
### 關於[Ubiquiti]
At [Ubiquiti](http://www.ui.com), our mission is to simplify I.T. We strive for technology UX perfection everywhere — from our web store shopping experience, to product packaging details, to frictionless setup and installation flows. As a team, we value autonomy, so we want you to bring your ownership mindset in our pursuit of creating the best user experience. You’ll be challenged to use your creative problem-solving skills and work backwards to address the highest touch-point UX issues for our users, finding points of leverage and reducing risk. We place emphasis on working together, fostering an environment of trust and transparency.

### 職缺要求
Responsibilities:
- Build RESTful APIs.
- Development application in embedded platform.
- Design Software Architecture.
- Network Programming.
- Work in cross functional teams with Frontend, Firmware, UX, QA etc.
- Deliver on-quality and on-time.
- Willing to share knowledge and code review
 
Qualifications:
- Expert in NodeJS (3+ years of experience)
- Expert of *nix system administration skills.
- Experience in building RESTful APIs.
- Experience with network programming (Sockets/TCP/IP)
- Familiar with RMDB. (Postgres/MySQL/MSSQL)
- Strong problem solving skills, responsive and flexible.
- Have code cleanliness, keep improving the code.
- Ability to work independently within a high talent team.
- Self-Starter willing to learn and apply new software skills.
- Excellent written and verbal communication skills.
 
Bonus:
- Experience using ORM Frameworks
- Experience in developing NVR/DVR-related products
- Experience in React/Redux or similar frameworks
- Experience in Express or Koa framework
- Understanding of security concepts.
- Understanding of WebRTC concepts.
 
### 薪資範圍
NT$ 1,300,000以上 (年薪）

### 工作福利

- 彈性上下班也可申請遠端WFH
- 免費午餐及水果
- 優於勞基法不扣薪事假病假
- 零食區全日免費提供飲品及美食
- 員工/眷屬團體保險及健檢
- 健身房及team building 補助

### 聯絡方式
請至官網 [Backend engineer-node.js](https://ubnt.applytojob.com/apply/kOpaOWFoo0/Backend-Engineer-Node)投遞履歷或寄至[hr.taiwan@ui.com](mailto:hr.taiwan@ui.com)
更多Backend 職缺：
[Backend engineer-node.js (Unifi-Talk )](https://ubnt.applytojob.com/apply/J76A1bqAGV/Backend-Engineer-Node-UnifiTalk-)
[Sr. Backend Engineer(Java)](https://ubnt.applytojob.com/apply/amnEzZvDku/Sr-Backend-EngineerJava)
[Access Backend Developer](https://ubnt.applytojob.com/apply/0wltR5cZd1/Access-BackendFW-Developer)

**Comment by gocreating** [comment]
# 不推這間的 Backend

非常不尊重 Candidate，花了3天下班時間寫的作業直接 Reject，追問原因後，只丟了一句「code跑不起來」就無聲無息了

**Comment by howardsun-tw** [comment]
補個面試作業不好的體驗
作業皆有完成需求甚至數個加分題
卻被丟一個「看起來是用最少時間寫出的東西」的理由拒絕
實在不能接受
