### ISSUE TITLE
[徵才] Better Self 專案成員招募

### ISSUE THREAD

**Issue by d9nielcoding** [b2etw/jobs#64]
# **🕵️‍♂️ Better Self 團隊徵人 🕵️‍♂️**

#前端 #後端 #React #Python

> 您現在收看的是「喂是中文台」，現在播放的是… Better Self 徵人節目！
**主要招募 前端 後端** (其他有興趣的夥伴也可洽談，但開發者優先)
有興趣再繼續往下，沒興趣的我幫您節省時間了，出口直走到底左轉！
> 

## 🤹‍♀️ **團隊成員** 👨‍🔬

一名全端開發者

一名產品設計師

一名數據分析師

一名數據分析顧問

以及一隻嘴砲仔（該成員自己說的）

## 📱 **產品介紹** 💻

> Better Self 是一款應用，一個社群，更是一群永遠追求進化的人們。
> 

好啦不嘴砲，我們正在開發能幫助使用者以最快速無痛的方式，紀錄生活、分析、優化生活，並成為更好的自己。希望在未來以，高隱私、AI對話式協助、社群媒合等面向，成為新世代的殺手級應用（？）
可參考此篇介紹 [https://better-self-app.notion.site/better-self-app/Better-Self-0694f6c3995f45589d6c26b39b77ae7d](https://www.notion.so/Better-Self-0694f6c3995f45589d6c26b39b77ae7d?pvs=21)

## 🧘‍♀️ **合作模式** 🚴‍♀️

**開會**：目前每週週日早上10:00例會，如果多數團隊成員有事情可調整。
**工作內容**：相當自由，你可以以任何形式進行貢獻。當然，我們跟「潛在成員的你」都希望產品能快速迭代，創造新的可能，因此也會有一定的進度期待。

## 🤓 **招募角色** 😎

**前端**：使用 Next.js 進行開發

**後端**：使用 Python 的 FastAPI 進行開發

使用者：我們也非常歡迎想要使用這類型 app 的你，透過加入使用者社群進行意見反饋，會得到最即時與開發者/產品設計者對話的機會，也能以使用者的角度，在建立這款「天使應用」的路上貢獻一己之力！

## 🎁 **你會獲得** 💰

- Better Point：因為團隊有 web3 背景，Better Self 項目採用 web3 常見的雙代幣模式：獎勵代幣與治理代幣，開發團隊/社群/參與者可透過積極行為獲得獎勵代幣 (Better Point)。
- 跟一些酷人合作的機會（真的很酷！）
- Side Project開發經驗（痾好像是廢話）

## 🤙 **報名方式** 📞

**報名方式**：[https://www.notion.so/better-self-app/9346d89fcc38445cb0dc58f7b392d2fd](https://www.notion.so/9346d89fcc38445cb0dc58f7b392d2fd?pvs=21)

**Comment by gocreating** [comment]
薪資範圍？

**Comment by d9nielcoding** [comment]
> 薪資範圍？
我們項目採用代幣經濟的模式～
您可以參考文中的「你會獲得」

**Comment by urayoru113** [comment]
所以這比較像是要找志同道合的人一起寫side project?

**Comment by d9nielcoding** [comment]
因為專案負責人離開團隊，所以暫時不招人，不好意思打擾大家了...
