### ISSUE TITLE
[徵才] 滿食空有限公司 / Jr. Backend / Sr. Full Stack

### ISSUE THREAD

**Issue by foospace** [b2etw/jobs#8]
# 公司名稱
滿食空股份有限公司

# 公司地址
105 台北市松山區近敦化民權

# 公司網站
https://eat.freezone.com.tw/jobC

# 職缺與薪資範圍
* Backend Engineer / 後端工程師 (40~60K/Month)
* Full Stack Engineer / 全端工程師 (60~100K/Month)

# 職務說明
## Backend Engineer / 後端工程師
* Work with functional teams to create a revolutionary smart retail system
* Develop core technologies such as free checkout, non-scan detection, automated store, and etc
* Collaborate closely with the data team to develop, test, and deploy analytical tools that implement a wide range of machine learning models
* Determine the software architecture and make high-level design choices

##  Full Stack Engineer / 全端工程師
* Work with functional teams to create a smart retail system
* Build large-scale data processing pipelines and predictive models
* Determine the software architecture and make high-level design choices
* Build and lead an extraordinary team of software development and data processing engineers
* Be closely involved in all major company decisions

# 職缺要求
#### Must Have
* 2年以上 JavaScript、Node.js 開發經驗
* 熟悉 Firebase等 serverless 服務
* 熟悉 Git flow
* 具有良好的開發習慣，能寫出高品質、可維護、可讀性高的程式碼
* Passion for learning and building. We highly value your ability and appetite for learning
* Desire to work with intelligent individuals in a fast-paced startup environment

#### Nice to Have
* 熟悉 React + Redux + Saga 框架
* 擁有 NDK 開發相關經驗
* 參與設計過「自動化CI/CD」的經驗
* 熟悉 Android 開發（Native、Java based）

#### Must Have
* 4年以上 Javascript、Node JS 開發經驗
* 熟悉 React JS + redux + saga 框架
* Android 開發經驗（Native、Java based）
* NDK 開發相關經驗
* 熟悉 Git flow
* 熟悉 Firebase 等 serverless 服務
* 自動化 CI/CD 相關經驗
* Able to communicate and co-work effectively with stakeholders
* Desire to work with intelligent individuals in a fast-paced startup environment

# 面試流程
* online test
* onsite interviews

# 公司介紹
自由食間是更聰明、更便利、且更懂你的無人零售通路。透過物聯網及人工智慧，我們要在對的時間地點裡提供對的東西給對的人；整合無人零售省去無謂的等待並提供最完善的服務。我們總是追求進步與改變，所以努力讓每一次的消費都能有最完美的體驗 。

We build an automated retail system with an exclusive shopping experience. With our technologies, much of the purchase, checkout, and payment steps associated with a retail transaction are completely automated. In the meantime, we focus on providing the right goods to the right people based on the behavioral data collected by our innovative system. Our vision is to provide the world's most pleasant shopping experience.

# 工作福利
We offer a competitive compensation package with equity included. Salary and job roles are all negotiable as working with top talents is always our first priority. We would love to hear from you!

* 一週4+天免費午晚餐（Free lunch & dinner）
* 24H零食飲料餵食（Unlimited snacks & beverage）
* Happy Friday啤酒日（Happy friday, beer day!）
* 有點不想回家的工作環境（chilled office enviroment）
* 每月2天WFH選擇（Monthly WFH policy）
* 彈性工時、彈性地點（Flexible hours & location）
* 員工認股選擇權（Stock option）

# 聯絡方式
**FooSpace Recruitment**
Contact｜Jessica
E-mail｜team@foospace.co

**Comment by JeremyShih** [comment]
24H零食飲料餵食（Unliimted snacks & beverage） --> Unlimted?
